"""add index

Revision ID: 9fa1a70e5d81
Revises: 2a1965bbed93
Create Date: 2026-02-01 16:55:04.415642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa1a70e5d81'
down_revision: Union[str, Sequence[str], None] = '2a1965bbed93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email_indx', 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email_indx', table_name='user')
    # ### end Alembic commands ###
